import os
from binance.client import AsyncClient, HistoricalKlinesType

TIME_WINDOW_1MINUTE = AsyncClient.KLINE_INTERVAL_1MINUTE
TIME_WINDOW_3MINUTE = AsyncClient.KLINE_INTERVAL_3MINUTE
TIME_WINDOW_5MINUTE = AsyncClient.KLINE_INTERVAL_5MINUTE
TIME_WINDOW_15MINUTE = AsyncClient.KLINE_INTERVAL_15MINUTE
TIME_WINDOW_30MINUTE = AsyncClient.KLINE_INTERVAL_30MINUTE
TIME_WINDOW_1HOUR = AsyncClient.KLINE_INTERVAL_1HOUR
TIME_WINDOW_2HOUR = AsyncClient.KLINE_INTERVAL_2HOUR
TIME_WINDOW_4HOUR = AsyncClient.KLINE_INTERVAL_4HOUR
TIME_WINDOW_6HOUR = AsyncClient.KLINE_INTERVAL_6HOUR
TIME_WINDOW_8HOUR = AsyncClient.KLINE_INTERVAL_8HOUR
TIME_WINDOW_12HOUR = AsyncClient.KLINE_INTERVAL_12HOUR
TIME_WINDOW_1DAY = AsyncClient.KLINE_INTERVAL_1DAY
TIME_WINDOW_3DAY = AsyncClient.KLINE_INTERVAL_3DAY
TIME_WINDOW_1WEEK = AsyncClient.KLINE_INTERVAL_1WEEK
TIME_WINDOW_1MONTH = AsyncClient.KLINE_INTERVAL_1MONTH


DEFAULT_TIME_WINDOW = TIME_WINDOW_1HOUR

WEIGHT_RATELIMIT_ERROR_CODE = -1003
WEIGHT_RATELIMIT_TIMEOUT_SECONDS = 20

DEFAULT_KLINES_TYPE = HistoricalKlinesType.SPOT

RISK_MARGIN = 3.0

SQLITE_EUR_PAIRS_DB_FILENAME = "Klines_1h.db"
SQLITE_EUR_PAIRS_DB_FILEPATH = os.path.join(os.getcwd(), "DBs", SQLITE_EUR_PAIRS_DB_FILENAME)
